[package]
name = "networth_db"
version = "0.1.0"
edition = "2018"

[dependencies]
calamine = "0.25.0"
dotenv = "0.15.0"
lazy_static = "1.5.0"
lopdf = { version = "0.34.0", features = ["pom", "pom_parser"] }
regex = "1.11.1"
tracing = "0.1.40"
