/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare const DATA_KEY_LEN: number

export declare function decodeKey(raw: string): Buffer

export declare function decrypt(key: Buffer, blob: Buffer): Buffer

export declare function decryptString(key: Buffer, blob: Buffer): string

export declare function encrypt(key: Buffer, plaintext: Buffer): Buffer

export declare function encryptString(key: Buffer, plaintext: string): Buffer

export declare function isEncrypted(blob: Buffer): boolean
