/* auto-generated by NAPI-RS */
/* eslint-disable */

export interface Account {
  id: string
  userId: string
  accountType: string
  bank: string
  variant: string | null
  label: string
  openingDate: string
  closingDate: string | null
  accountNumber: string
  passwords: Array<string>
  mail: MailRules | null
  statement: StatementRules | null
  createdAt: string
  updatedAt: string
}

export interface AccountTransactions {
  period: string
  isAnnual: boolean
  rows: Array<TransactionRow>
}

export interface BalanceGap {
  month: string
  status: string
}

export interface Bank {
  key: string
  bank: string
  variant?: string
  accountType: string
}

export interface CoverageGap {
  start: string
  end: string
  balancesMatch?: boolean
}

export interface CoverageSegment {
  start: string
  end: string
  approximate?: boolean
}

export declare function deleteAccountStatements(run: StatementsRun, accountId: string, dataKey?: Buffer | undefined | null): ProcessResult

export declare function initStatementsRuntime(config?: StatementsRuntimeConfig | undefined | null): void

export interface JobScope {
  accountId: string | null
  financialYear: string | null
}

export declare function listBanks(): Array<Bank>

export interface MailRules {
  subjects: Array<string>
  bodyContains: Array<string>
  fromAddresses: Array<string>
}

export declare function processPipeline(run: StatementsRun, dataKey?: Buffer | undefined | null, debugTrace?: boolean | undefined | null, shouldCancel?: () => boolean): ProcessResult

export interface ProcessResult {
  ok: boolean
  reason?: string
  warnings: Array<StatementWarning>
  logs?: string
}

export declare function processUpload(run: StatementsRun, upload: ProcessUploadInput, dataKey?: Buffer | undefined | null, debugTrace?: boolean | undefined | null, shouldCancel?: () => boolean): ProcessResult

export interface ProcessUploadInput {
  accountId: string
  format: string
  statementDate: string | null
}

export declare function readAccountStatements(input: ReadAccountStatementsInput): StatementList

export interface ReadAccountStatementsInput {
  userId: string
  dataKey: Buffer | null | null
  account: Account
}

export declare function readAccountTransactions(input: ReadAccountTransactionsInput): Array<AccountTransactions>

export interface ReadAccountTransactionsInput {
  userId: string
  dataKey: Buffer | null | null
  account: Account
}

export declare function readStatementFile(input: StatementFileInput): Buffer | null

export interface SourceNapi {
  id: string
  type: 'thunderbird' | 'email'
  label: string
  profile: string | null
  host: string | null
  port: number | null
  username: string | null
  password: string | null
  folder: string | null
  useSsl: boolean | null
}

export interface Statement {
  accountId: string
  kind: StatementKind
  period: string
  statementDate: string
  formats: Array<string>
  periodStart?: string
  periodEnd?: string
}

export interface StatementCoverage {
  start?: string
  end?: string
  segments: Array<CoverageSegment>
  gaps: Array<CoverageGap>
  months: Array<string>
  periodCount: number
}

export declare function statementFileExists(input: StatementFileInput): boolean

export interface StatementFileInput {
  userId: string
  dataKey: Buffer | null | null
  accountType: string
  accountId: string
  format: string
  statementDate: string | null
  filename: string | null
}

export declare enum StatementKind {
  Monthly = 0,
  Annual = 1,
}

export interface StatementList {
  available: boolean
  statementCount: number
  starting?: string
  ending?: string
  formats: Array<string>
  coverage: StatementCoverage
  statements: Array<Statement>
  balanceGaps: Array<BalanceGap>
}

export interface StatementRules {
  textContains: Array<string>
  textNotContains: Array<string>
}

export interface StatementsRun {
  userId: string
  scope: JobScope
  accounts: Array<Account>
  sources: Array<SourceNapi>
}

export interface StatementsRuntimeConfig {
  filestorePath?: string
  encryptAtRest?: boolean
}

export interface StatementWarning {
  kind: string
  message: string
  account: string
  sourceFile: string
  textContains: Array<string>
}

export interface TransactionRow {
  date: string
  description: string
  refNo: string
  credited: string
  debited: string
  sourceFile: string
}

export declare function writeUpload(input: WriteUploadInput): WriteUploadResult

export interface WriteUploadInput {
  userId: string
  dataKey: Buffer | null | null
  accountType: string
  accountId: string
  format: string
  statementDate: string | null
  filename: string
  data: Buffer
  passwords: Array<string>
}

export interface WriteUploadResult {
  relative: string
}
