//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "staged_transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub import_id: Uuid,
    pub date: DateTime,
    #[sea_orm(column_type = "Float")]
    pub amount: f32,
    #[sea_orm(column_type = "Float")]
    pub balance: f32,
    pub ref_no: String,
    pub description: String,
    pub sequence_number: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::imports::Entity",
        from = "Column::ImportId",
        to = "super::imports::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Imports,
}

impl Related<super::imports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Imports.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
