/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class Logger {
  debug(msg: string, context?: LogContext): void;
  info(msg: string, context?: LogContext): void;
  warn(msg: string, context?: LogContext): void;
  error(msg: string, context?: LogContext): void;
  child(context: LogContext): Logger;
}
export type LoggerHandle = Logger;

export declare class RayManager {
  constructor();
  setActor(actorId: string): void;
  current(): RayContext;
  require(): string;
}
export type RayHandle = RayManager;

export declare function createLogger(options: CreateLoggerOptions): Logger;

export interface CreateLoggerOptions {
  level: LogLevel;
  app: string;
  destination?: LogDestination;
  defaultContext?: LogContext;
}

export type LogDestination = "console" | "stdout" | "stderr";

export type LogLevel = "debug" | "info" | "warn" | "error";

export interface RayContext {
  rayId?: string;
  actorId?: string;
}
